version: '3.7'
services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    volumes:
      - ./Test_backend:/usr/src/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis
    restart: always
    command: redis-server
  celery:
    build: .
    command: celery -A Test_project worker --loglevel=INFO
    volumes:
      - ./Test_backend:/usr/src/backend
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
    restart: always
volumes:
  postgres_data: